controller_manager:  
  ros__parameters:  
    update_rate: 100  
    use_sim_time: true  

joint_state_broadcaster:
  type: joint_state_broadcaster/JointStateBroadcaster
  
    diff_cont:  
      type: diff_drive_controller/DiffDriveController  
      parameters:  
        left_wheel_names: ["drivewhl_l_joint"]  
        right_wheel_names: ["drivewhl_r_joint"]  
        wheel_separation: ${2 * (base_radius + wheel_width)}  
        wheel_radius: ${wheel_radius}  
        odom_frame_id: odom  
        base_frame_id: base_link  
        publish_rate: 50.0  